<?php
	$this->load->view('modal/modal_sign');
    $this->load->view('tamplate/header');
    $this->load->view('tamplate/navbar');
    if(@$content!='')
    {
    $this->load->view(@$content);
    }
?>